DELETE http://localhost:4001/api/tickets/be71961b-552d-4e24-8721-e5d84f419196 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0MGIzNmJjMS03MGM3LTQ1OWItYTQ5OC02MDAyNzUxMDk1YTIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzQwMjAzMDksImV4cCI6MTczNDAyMzkwOX0.WAAlwScuNZNV-i4vKYDgyx5gboVzVyiV-5adN2rEaD8